
services:
  db:

    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent' ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password



    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=gecodb
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/init.sql
      #- db-data:/var/lib/mysql
   # command: 'mysql -u root -p < create.sql'
    expose:
      - 3306
      - 33060
  web:
    build:
      context: backend
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    restart: always
    environment:
      - APP_ENV = PROD
    secrets:
      - db-password
    stop_signal: SIGINT
    ports:
      - '5000:5000'

    networks:
      - backnet
      #- frontnet
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:


secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
